version: '3'
services:
  frontend:
    build: .
    container_name: valevaledor-frontend
    restart: always
    expose:
      - 3000
    environment:
      VIRTUAL_HOST: dev.valevaledor.com,www.dev.valevaledor.com
      LETSENCRYPT_HOST: dev.valevaledor.com,www.dev.valevaledor.com
    networks:
      - valevaledor_nginx
networks:
  valevaledor_nginx:
    external: true